<?xml version="1.0"?>
<package format="3">
  <name>fsc_autopilot_ros</name>
  <version>0.3.0</version>
  <description>Tracking Control</description>

  <maintainer email="hellston20a@gmail.com">Hs293Go</maintainer>
  <license>MIT</license>

  <!-- ROS 2 build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- General dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_eigen</depend>
  <depend>mavros</depend>
  <depend>mavros_msgs</depend>
  <depend>fsc_autopilot</depend>
  <depend>fsc_autopilot_msgs</depend>

  <!-- Message generation dependencies -->
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Required for interface packages -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
